name: CI Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build pkg-config \
            libasound2-dev libx11-dev libxext-dev libxinerama-dev libxrandr-dev \
            libxcomposite-dev libxcursor-dev libxrender-dev \
            libfreetype6-dev libfontconfig1-dev \
            libgl1-mesa-dev libjack-jackd2-dev

      - name: Install Ninja (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install ninja || true

      - name: Configure (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: cmake --preset linux-ninja-release

      - name: Configure (macOS)
        if: matrix.os == 'macos-latest'
        run: cmake --preset macos-ninja-release

      - name: Build tests
        run: |
          cmake --build build/linux-ninja-release --target MetroGnome_Tests || \
          cmake --build build/macos-ninja-release --target MetroGnome_Tests

      - name: Run tests
        run: |
          ctest --test-dir build/linux-ninja-release --output-on-failure || \
          ctest --test-dir build/macos-ninja-release --output-on-failure

      - name: Build plugin target (optional)
        run: |
          cmake --build build/linux-ninja-release --target MetroGnome || \
          cmake --build build/macos-ninja-release --target MetroGnome
